# Generated by Django 3.2.5 on 2021-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210918_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Categoryname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Productname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Subcategoryname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
