# Generated by Django 3.2.5 on 2021-09-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210918_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='state',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='state',
        ),
    ]
