# Generated by Django 3.2.5 on 2021-09-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210920_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ManyToManyField(to='products.Category'),
        ),
    ]
